apiVersion: v1
kind: PersistentVolume
metadata:
  name: kumparan-storage-elasticsearch
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: kumparan-storage-elasticsearch
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: DirectoryOrCreate
    path: "/home/apps/kumparan/storage-elasticsearch"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-kumparan-storage-elasticsearch
  namespace: kumparan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kumparan-storage-elasticsearch
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-elasticsearch
  namespace: kumparan
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: p-kumparan
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kumparan
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.0.0
          imagePullPolicy: Always
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: http.cors.enabled
              value: "true"
            - name: http.cors.allow-origin
              value: "*"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: claim-kumparan-storage-elasticsearch
      volumes:
        - name: claim-kumparan-storage-elasticsearch
          persistentVolumeClaim:
            claimName: claim-kumparan-storage-elasticsearch
