apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kumparan
  namespace: kumparan
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kumparan-api.onhost.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-kumparan
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-kumparan
  namespace: kumparan
spec:
  selector:
    app: kumparan
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: p-kumparan
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumparan
  namespace: kumparan
spec:
  selector:
    matchLabels:
      app: kumparan
  replicas: 1
  template:
    metadata:
      labels:
        app: kumparan
    spec:
      containers:
        - name: kumparan
          image: gcr.io/utils-id/kumparan:v0.0.1
          imagePullPolicy: Always
          env:
            - name: URL_MONGO
              value: mongodb://root:root@svc-mongodb:27017/kumparan?authSource=admin
            - name: URL_REDIS
              value: redis://svc-redis:6379
            - name: URL_ELASTICSEARCH
              value: http://svc-elasticsearch:9200
