apiVersion: v1
kind: Service
metadata:
  name: svc-redis
  namespace: kumparan
spec:
  selector:
    app: redis
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: p-kumparan
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kumparan
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          imagePullPolicy: Always
          command:
            [
              "redis-server",
              "--bind",
              "0.0.0.0",
              "--port",
              "6379",
              "--protected-mode",
              "no",
            ]
# redis-server --bind 0.0.0.0 --port 6379 --protected-mode no
